title: Burak. | Stay With Research
description: > # this means to ignore newlines until "baseurl:"
  You can find my published papers with their derivations, MATLAB algorithms, and simulation result values and
  lecturing of some of the important topics within the context of wireless communication technologies.
permalink: "https://burakozpoyraz.github.io/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Burak Özpoyraz
author-img: ProfilePhoto.jpeg
about-author:
  I am Ph.D. student in Koç University - Electrical and Electronics Engineering Department. My major working fields are wireless communication
  technologies including physical layer solutions of future mobile technologies 5G / 6G and beyond, deep learning, and software development.
social-twitter: burakozpoyraz7
social-website: http://www.burakozpoyraz.com/
social-github: burakozpoyraz
social-linkedin: burak-ozpoyraz
social-email: burakozpoyraz@gmail.com

# Disqus
discus-identifier:

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 2
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
